---
- name: import Amazon Corretto RPM GPG key
  ansible.builtin.rpm_key:
    key: https://yum.corretto.aws/corretto.key
    state: present
  when: java_configure_corretto_repo
  tags: ['java']

- name: configure Amazon Corretto repository
  ansible.builtin.get_url:
    url: https://yum.corretto.aws/corretto.repo
    dest: /etc/yum.repos.d/corretto.repo
    owner: root
    group: root
    mode: '0644'
  when: java_configure_corretto_repo
  tags: ['java']

- name: install java packages
  ansible.builtin.dnf:
    name: "{{ java_versions | map('regex_replace', '^(.*)$', 'java-\\1-' + java_provider) | list }}"
    state: present
  when: java_install_jre
  tags: ['java']

- name: install java devel packages
  ansible.builtin.dnf:
    name: "{{ java_versions | map('regex_replace', '^(.*)$', 'java-\\1-' + java_provider + '-devel') | list }}"
    state: present
  when: java_install_devel
  tags: ['java']

- name: set default java version
  ansible.builtin.command:
    cmd: >-
      alternatives --set java
      /usr/lib/jvm/java-{{ java_default_version }}-{{ java_provider }}{{ (java_provider == 'amazon-corretto') | ternary('.x86_64', '') }}{{ (java_default_version == '1.8.0') | ternary('/jre/bin/java', '/bin/java') }}
  changed_when: false
  when: java_set_default_version
  tags: ['java']
